import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import './cover.css'
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

import NextTopLoader from "nextjs-toploader";
// import Loader from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-100">
      <body
        className={`${inter.className} d-flex h-100 text-center text-white bg-black`}
      >
        <NextTopLoader />

        <div className="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
          <NavBar />

          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
